using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Senior2.Api.Services
{
    public class ReportService
    {
        public byte[] GenerateReportPdf(
            int users,
            int trips,
            int reviews,
            int suggestions)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header()
                        .Text("AHLA BHAL TALLEH - Platform Report")
                        .FontSize(22)
                        .Bold();

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Generated At: {DateTime.Now}");
                        col.Item().Text($"Total Users: {users}");
                        col.Item().Text($"Total Trips: {trips}");
                        col.Item().Text($"Total Reviews: {reviews}");
                        col.Item().Text($"Total Suggestions: {suggestions}");
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Admin Dashboard");
                });
            }).GeneratePdf();
        }
    }
}
