// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senior2.Api.Data;

#nullable disable

namespace Senior2.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218214713_UpdateLizaStructure")]
    partial class UpdateLizaStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/categories/activities.jpg",
                            Name = "Activities",
                            Slug = "activities"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/categories/guesthouses.jpg",
                            Name = "Guesthouses",
                            Slug = "guesthouses"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/categories/hotels.jpg",
                            Name = "Hotels",
                            Slug = "hotels"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/categories/restaurants.jpg",
                            Name = "Restaurants",
                            Slug = "restaurants"
                        });
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Baatara Gorge Waterfall (Balou’ Balaa) is a spectacular waterfall that drops into a deep sinkhole through three natural rock bridges in Tannourine.\r\n.",
                            ImageUrl = "/images/activities/hiking/balou3.jpg",
                            Location = "In Tannourine, North Lebanon",
                            Name = "Balou’ Balaa",
                            Price = 20m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Discover the breathtaking limestone caves of Jeita.",
                            ImageUrl = "/images/activities/hiking/jeita.jpg",
                            Location = "Jeita, Lebanon",
                            Name = "Jeita Grotto Visit",
                            Price = 15m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Discover the Enchanting Chouwen Lake: A Hidden Gem in Lebanon.",
                            ImageUrl = "/images/activities/hiking/chouwen_hike.jpg",
                            Location = "Keserwan District,Mount Lebanon",
                            Name = "Hiking in chouwen",
                            Price = 20m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Hiking in Wadi Qannoubine offers breathtaking cliffs, ancient monasteries, and peaceful mountain scenery in the heart of Lebanon’s historic valley.\r\n.",
                            ImageUrl = "/images/activities/hiking/wadi-qanoubine.jpg",
                            Location = "North Lebanon near Bcharre, Lebanon",
                            Name = "Hiking in wadi qanoubine",
                            Price = 20m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Traditional Lebanese mountain guesthouse with scenic views.",
                            ImageUrl = "/images/guesthouses/beit-trad/beitTrad_livingRoom.jpg",
                            Location = "Broummana, Lebanon",
                            Name = "Beit Trad Guesthouse",
                            Price = 80m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Charming stay surrounded by nature.",
                            ImageUrl = "/images/guesthouses/charme.jpg",
                            Location = "Beit Mery, Lebanon",
                            Name = "Charme Guesthouse",
                            Price = 95m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Luxury 5-star hotel overlooking the Mediterranean Sea.",
                            ImageUrl = "/images/hotels/phoenicia.jpg",
                            Location = "Beirut, Lebanon",
                            Name = "Phoenicia Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Authentic Lebanese fine dining experience.",
                            ImageUrl = "/images/restaurants/emsherif.jpg",
                            Location = "Downtown Beirut, Lebanon",
                            Name = "Em Sherif Restaurant",
                            Price = 50m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Babel is a modern Lebanese restaurant known for its upscale ambiance.",
                            ImageUrl = "/images/restaurants/Bebabel.jpg",
                            Location = "Downtown Beirut, Lebanon",
                            Name = "Bebabel",
                            Price = 50m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Babel Dbayeh is an upscale Lebanese restaurant known for fresh seafood and elegant dining.",
                            ImageUrl = "/images/restaurants/Babel.jpg",
                            Location = "Dbayeh, Lebanon",
                            Name = "Babel Bay",
                            Price = 50m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Al Beiruti is a popular Lebanese restaurant serving traditional mezze and grilled dishes in a lively, authentic atmosphere.",
                            ImageUrl = "/images/restaurants/Albeiruti.jpg",
                            Location = "Downtown Beirut, Lebanon",
                            Name = "Al beiruti ",
                            Price = 50m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Liza is an elegant Lebanese-Mediterranean restaurant in **Beirut** known for beautifully plated traditional dishes with a modern twist.",
                            ImageUrl = "/images/restaurants/Liza.jpg",
                            Location = "Achrafieh Beirut, Lebanon",
                            Name = " Liza ",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.HasOne("Senior2.Api.Models.ActivityType", "ActivityType")
                        .WithMany("Places")
                        .HasForeignKey("ActivityTypeId");

                    b.HasOne("Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("ActivityTypes");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
