// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senior2.Api.Data;

#nullable disable

namespace Senior2.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220210444_AddActivityPlaces")]
    partial class AddActivityPlaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/categories/activities.jpg",
                            Name = "Activities",
                            Slug = "activities"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/categories/guesthouses.jpg",
                            Name = "Guesthouses",
                            Slug = "guesthouses"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/categories/hotels.jpg",
                            Name = "Hotels",
                            Slug = "hotels"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/categories/restaurants.jpg",
                            Name = "Restaurants",
                            Slug = "restaurants"
                        });
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ActivityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/hiking/chouwen_hike.jpg",
                            Name = "Hiking",
                            Slug = "hiking"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/swimming/swimming.jpg",
                            Name = "Swimming",
                            Slug = "swimming"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/skiing/skiing.jpg",
                            Name = "Skiing",
                            Slug = "skiing"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/football/football.jpg",
                            Name = "Football",
                            Slug = "Football"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/padel/padel.jpg",
                            Name = "Padel",
                            Slug = "Padel"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/tennis/tennis.jpg",
                            Name = "Tennis",
                            Slug = "Teniis"
                        });
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Traditional Lebanese mountain guesthouse.",
                            ImageUrl = "/images/guesthouses/beit-trad/beitTrad_livingRoom.jpg",
                            Location = "Broummana, Lebanon",
                            Name = "Beit Trad Guesthouse",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Charming stay surrounded by nature.",
                            ImageUrl = "/images/guesthouses/charme guesthouse/charme_overview.jpg",
                            Location = "Cedars, Lebanon",
                            Name = "Charme Guesthouse",
                            Price = 95m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A charming guesthouse in Byblos.",
                            ImageUrl = "/images/guesthouses/Beit Faris.jpg",
                            Location = "Byblos, Lebanon",
                            Name = "Beit Faris",
                            Price = 95m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Beautiful heritage guesthouse.",
                            ImageUrl = "/images/guesthouses/beitToureef/beitToureef_Overview.jpg",
                            Location = "Gemmayzeh, Lebanon",
                            Name = "Beit Toureef",
                            Price = 95m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Warm village guesthouse in Mtein.",
                            ImageUrl = "/images/guesthouses/beit-jedde/beitJeddi_Overview.jpg",
                            Location = "Mtein, Lebanon",
                            Name = "Beit Jeddé",
                            Price = 95m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Cozy boutique guesthouse by the sea.",
                            ImageUrl = "/images/guesthouses/beit-elBarbara/beit-elBarbara.jpg",
                            Location = "Barbara, Lebanon",
                            Name = "Beit El Berbara",
                            Price = 95m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Luxury 5-star hotel.",
                            ImageUrl = "/images/hotels/phoenicia.jpg",
                            Location = "Beirut",
                            Name = "Phoenicia Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Modern business hotel.",
                            ImageUrl = "/images/hotels/radisson.jpg",
                            Location = "Verdun Beirut",
                            Name = "Radisson Blu Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Trendy boutique hotel.",
                            ImageUrl = "/images/hotels/The Smallville Hotel.jpg",
                            Location = "Badaro",
                            Name = "The Smallville Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Luxury seaside resort.",
                            ImageUrl = "/images/hotels/Kempinski Summerland Hotel & Resort Beirut.jpg",
                            Location = "Jnah Beirut",
                            Name = "Kempinski Summerland",
                            Price = 250m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "High-end luxury hotel.",
                            ImageUrl = "/images/hotels/Four Seasons Hotel Beirut.jpg",
                            Location = "Downtown Beirut",
                            Name = "Four Seasons Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Elegant boutique hotel.",
                            ImageUrl = "/images/hotels/Le Gabriel.jpg",
                            Location = "Achrafieh",
                            Name = "Le Gabriel Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Authentic Lebanese fine dining.",
                            ImageUrl = "/images/restaurants/emsherif.jpg",
                            Location = "Beirut",
                            Name = "Em Sherif",
                            Price = 50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Modern Lebanese restaurant.",
                            ImageUrl = "/images/restaurants/Bebabel.jpg",
                            Location = "Beirut",
                            Name = "Bebabel",
                            Price = 50m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Upscale seafood dining.",
                            ImageUrl = "/images/restaurants/Babel.jpg",
                            Location = "Dbayeh",
                            Name = "Babel Bay",
                            Price = 50m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Traditional mezze and grills.",
                            ImageUrl = "/images/restaurants/Albeiruti.jpg",
                            Location = "Beirut",
                            Name = "Al Beiruti",
                            Price = 50m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Elegant Lebanese-Mediterranean.",
                            ImageUrl = "/images/restaurants/Liza.jpg",
                            Location = "Achrafieh",
                            Name = "Liza",
                            Price = 50m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Japanese sushi & fusion.",
                            ImageUrl = "/images/restaurants/Kampai.jpg",
                            Location = "Beirut",
                            Name = "Kampai",
                            Price = 50m
                        },
                        new
                        {
                            Id = 19,
                            ActivityTypeId = 2,
                            CategoryId = 1,
                            Description = "Popular swimming destination in Beirut.",
                            ImageUrl = "/images/activities/swimming/sporting.jpg",
                            Location = "Beirut",
                            Name = "Sporting Beach",
                            Price = 25m
                        },
                        new
                        {
                            Id = 20,
                            ActivityTypeId = 3,
                            CategoryId = 1,
                            Description = "Best skiing destination in Lebanon.",
                            ImageUrl = "/images/activities/skiing/mzaar.jpg",
                            Location = "Kfardebian",
                            Name = "Mzaar Ski Resort",
                            Price = 60m
                        },
                        new
                        {
                            Id = 21,
                            ActivityTypeId = 1,
                            CategoryId = 1,
                            Description = "Beautiful hiking area with river pools.",
                            ImageUrl = "/images/activities/hiking/chouwen.jpg",
                            Location = "Jbeil",
                            Name = "Chouwen Hiking Trail",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.HasOne("Senior2.Api.Models.ActivityType", "ActivityType")
                        .WithMany("Places")
                        .HasForeignKey("ActivityTypeId");

                    b.HasOne("Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("ActivityTypes");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
