// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senior2.Api.Data;

#nullable disable

namespace Senior2.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227213902_ProfileSystemsFix")]
    partial class ProfileSystemsFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/categories/activities.jpg",
                            Name = "Activities",
                            Slug = "activities"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/categories/guesthouses.jpg",
                            Name = "Guesthouses",
                            Slug = "guesthouses"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/categories/hotels.jpg",
                            Name = "Hotels",
                            Slug = "hotels"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/categories/restaurants.jpg",
                            Name = "Restaurants",
                            Slug = "restaurants"
                        });
                });

            modelBuilder.Entity("JourneyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JourneyEntries");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ActivityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/hiking/chouwen_hike.jpg",
                            Name = "Hiking",
                            Slug = "hiking"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/swimming/swimming.jpg",
                            Name = "Swimming",
                            Slug = "swimming"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/skiing/skiing.jpg",
                            Name = "Skiing",
                            Slug = "skiing"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/football/football.jpg",
                            Name = "Football",
                            Slug = "football"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/padel/padel.jpg",
                            Name = "Padel",
                            Slug = "padel"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/tennis/tennis.jpg",
                            Name = "Tennis",
                            Slug = "tennis"
                        });
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Traditional Lebanese mountain guesthouse.",
                            ImageUrl = "/images/guesthouses/beit-trad/beitTrad_livingRoom.jpg",
                            Location = "Broummana, Lebanon",
                            Name = "Beit Trad Guesthouse",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Charming stay surrounded by nature.",
                            ImageUrl = "/images/guesthouses/charme guesthouse/charme_overview.jpg",
                            Location = "Cedars, Lebanon",
                            Name = "Charme Guesthouse",
                            Price = 95m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A charming guesthouse in Byblos.",
                            ImageUrl = "/images/guesthouses/Beit Faris.jpg",
                            Location = "Byblos, Lebanon",
                            Name = "Beit Faris",
                            Price = 95m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Beautiful heritage guesthouse.",
                            ImageUrl = "/images/guesthouses/beitToureef/beitToureef_Overview.jpg",
                            Location = "Gemmayzeh, Lebanon",
                            Name = "Beit Toureef",
                            Price = 95m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Warm village guesthouse in Mtein.",
                            ImageUrl = "/images/guesthouses/beit-jedde/beitJeddi_Overview.jpg",
                            Location = "Mtein, Lebanon",
                            Name = "Beit Jeddé",
                            Price = 95m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Cozy boutique guesthouse by the sea.",
                            ImageUrl = "/images/guesthouses/beit-elBarbara/beit-elBarbara.jpg",
                            Location = "Barbara, Lebanon",
                            Name = "Beit El Berbara",
                            Price = 95m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Luxury 5-star hotel.",
                            ImageUrl = "/images/hotels/phoenicia.jpg",
                            Location = "Beirut",
                            Name = "Phoenicia Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Modern business hotel.",
                            ImageUrl = "/images/hotels/radisson.jpg",
                            Location = "Verdun Beirut",
                            Name = "Radisson Blu Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Trendy boutique hotel.",
                            ImageUrl = "/images/hotels/The Smallville Hotel.jpg",
                            Location = "Badaro",
                            Name = "The Smallville Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Luxury seaside resort.",
                            ImageUrl = "/images/hotels/Kempinski Summerland Hotel & Resort Beirut.jpg",
                            Location = "Jnah Beirut",
                            Name = "Kempinski Summerland",
                            Price = 250m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "High-end luxury hotel.",
                            ImageUrl = "/images/hotels/Four Seasons Hotel Beirut.jpg",
                            Location = "Downtown Beirut",
                            Name = "Four Seasons Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Elegant boutique hotel.",
                            ImageUrl = "/images/hotels/Le Gabriel.jpg",
                            Location = "Achrafieh",
                            Name = "Le Gabriel Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Authentic Lebanese fine dining.",
                            ImageUrl = "/images/restaurants/emsherif.jpg",
                            Location = "Beirut",
                            Name = "Em Sherif",
                            Price = 50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Modern Lebanese restaurant.",
                            ImageUrl = "/images/restaurants/Bebabel.jpg",
                            Location = "Beirut",
                            Name = "Bebabel",
                            Price = 50m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Upscale seafood dining.",
                            ImageUrl = "/images/restaurants/Babel.jpg",
                            Location = "Dbayeh",
                            Name = "Babel Bay",
                            Price = 50m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Traditional mezze and grills.",
                            ImageUrl = "/images/restaurants/Albeiruti.jpg",
                            Location = "Beirut",
                            Name = "Al Beiruti",
                            Price = 50m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Elegant Lebanese-Mediterranean.",
                            ImageUrl = "/images/restaurants/Liza.jpg",
                            Location = "Achrafieh",
                            Name = "Liza",
                            Price = 50m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Japanese sushi & fusion.",
                            ImageUrl = "/images/restaurants/Kampai.jpg",
                            Location = "Beirut",
                            Name = "Kampai",
                            Price = 50m
                        },
                        new
                        {
                            Id = 19,
                            ActivityTypeId = 2,
                            CategoryId = 1,
                            Description = "Popular swimming destination in Beirut.",
                            ImageUrl = "/images/activities/swimming/movenpick.jpg",
                            Location = "Beirut",
                            Name = "Movenpick Beach",
                            Price = 25m
                        },
                        new
                        {
                            Id = 22,
                            ActivityTypeId = 2,
                            CategoryId = 1,
                            Description = "Popular swimming destination in Beirut.",
                            ImageUrl = "/images/activities/swimming/sporting.jpg",
                            Location = "Beirut",
                            Name = "Sporting Beach",
                            Price = 25m
                        },
                        new
                        {
                            Id = 23,
                            ActivityTypeId = 2,
                            CategoryId = 1,
                            Description = "Popular swimming destination in batroun.",
                            ImageUrl = "/images/activities/swimming/blubay.jpg",
                            Location = "batroun",
                            Name = "Blubay Beach",
                            Price = 25m
                        },
                        new
                        {
                            Id = 24,
                            ActivityTypeId = 2,
                            CategoryId = 1,
                            Description = "Popular swimming destination in tyree.",
                            ImageUrl = "/images/activities/swimming/tyree.jpg",
                            Location = "South Lebanon (Sour)",
                            Name = "Tyree Beach",
                            Price = 25m
                        },
                        new
                        {
                            Id = 25,
                            ActivityTypeId = 2,
                            CategoryId = 1,
                            Description = "Popular swimming destination in anfeh.",
                            ImageUrl = "/images/activities/swimming/tahetelrich.jpg",
                            Location = "Anfeh (North Lebanon)",
                            Name = "Tahet el rich Beach",
                            Price = 25m
                        },
                        new
                        {
                            Id = 26,
                            ActivityTypeId = 2,
                            CategoryId = 1,
                            Description = "Popular swimming destination in jiyeh.",
                            ImageUrl = "/images/activities/swimming/lazyb.jpg",
                            Location = "Jiyeh, South of Beirut (Mount Lebanon)",
                            Name = "Lazy B  Beach",
                            Price = 25m
                        },
                        new
                        {
                            Id = 20,
                            ActivityTypeId = 3,
                            CategoryId = 1,
                            Description = "Best skiing destination in Lebanon.",
                            ImageUrl = "/images/activities/skiing/mzaarSkiResort.jpg",
                            Location = "Kfardebian",
                            Name = "Mzaar Ski Resort",
                            Price = 60m
                        },
                        new
                        {
                            Id = 27,
                            ActivityTypeId = 3,
                            CategoryId = 1,
                            Description = "Best skiing destination in Lebanon.",
                            ImageUrl = "/images/activities/skiing/cedarsSkiResort.jpg",
                            Location = "arz",
                            Name = "Cedars Ski Resort",
                            Price = 60m
                        },
                        new
                        {
                            Id = 28,
                            ActivityTypeId = 3,
                            CategoryId = 1,
                            Description = "Best skiing destination in Lebanon.",
                            ImageUrl = "/images/activities/skiing/laqlouqSkiResort.jpg",
                            Location = "laqlouq",
                            Name = "Laqlouq Ski Resort",
                            Price = 60m
                        },
                        new
                        {
                            Id = 29,
                            ActivityTypeId = 3,
                            CategoryId = 1,
                            Description = "Best skiing destination in Lebanon.",
                            ImageUrl = "/images/activities/skiing/zaarour.jpg",
                            Location = "zaarour",
                            Name = "Zaarour Ski Resort",
                            Price = 60m
                        },
                        new
                        {
                            Id = 21,
                            ActivityTypeId = 1,
                            CategoryId = 1,
                            Description = "Beautiful hiking area with river pools.",
                            ImageUrl = "/images/activities/hiking/chouwen_hike.jpg",
                            Location = "Jbeil",
                            Name = "Chouwen Hiking Trail",
                            Price = 0m
                        },
                        new
                        {
                            Id = 30,
                            ActivityTypeId = 1,
                            CategoryId = 1,
                            Description = "A UNESCO-listed valley known for dramatic cliffs, ancient monasteries, and peaceful nature trails — one of the most iconic hikes in Lebanon.",
                            ImageUrl = "/images/activities/hiking/wadi-qadisha.jpg",
                            Location = "North Lebanon",
                            Name = "Wadi Qadisha Hiking Trail",
                            Price = 0m
                        },
                        new
                        {
                            Id = 31,
                            ActivityTypeId = 1,
                            CategoryId = 1,
                            Description = "A beautiful cedar forest with marked trails, fresh air, and panoramic mountain views — perfect for nature lovers.",
                            ImageUrl = "/images/activities/hiking/tannourine.jpg",
                            Location = "North Lebanon",
                            Name = "Tannourine hiking Trail",
                            Price = 0m
                        },
                        new
                        {
                            Id = 32,
                            ActivityTypeId = 1,
                            CategoryId = 1,
                            Description = "A spectacular natural sinkhole with waterfalls and bridges — short hike but incredible views, especially in spring.",
                            ImageUrl = "/images/activities/hiking/balou3.jpg",
                            Location = "North Lebanon",
                            Name = "Balou balaa hiking Trail",
                            Price = 0m
                        },
                        new
                        {
                            Id = 33,
                            ActivityTypeId = 1,
                            CategoryId = 1,
                            Description = "A large protected area with rich biodiversity, cool weather, and multiple hiking trails ranging from easy to advanced.",
                            ImageUrl = "/images/activities/hiking/ehden.jpg",
                            Location = "North Lebanon",
                            Name = "Ehden  hiking Trail",
                            Price = 0m
                        },
                        new
                        {
                            Id = 34,
                            ActivityTypeId = 1,
                            CategoryId = 1,
                            Description = "The largest nature reserve in Lebanon — famous for cedar trees, mountain landscapes, and long scenic trails.",
                            ImageUrl = "/images/activities/hiking/chouf.jpg",
                            Location = "Mount Lebanon",
                            Name = "Chouf hiking Trail",
                            Price = 0m
                        },
                        new
                        {
                            Id = 35,
                            ActivityTypeId = 5,
                            CategoryId = 1,
                            Description = "High-quality courts, popular among regular players.",
                            ImageUrl = "/images/activities/padel/the padelist.jpg",
                            Location = "zalka beirut Lebanon",
                            Name = "The padelist",
                            Price = 0m
                        },
                        new
                        {
                            Id = 36,
                            ActivityTypeId = 5,
                            CategoryId = 1,
                            Description = " Trendy location near the sea — great atmosphere and central location.",
                            ImageUrl = "/images/activities/padel/the padel club.jpg",
                            Location = "Beirut Waterfront (BIEL)",
                            Name = "The Padel Club",
                            Price = 0m
                        },
                        new
                        {
                            Id = 37,
                            ActivityTypeId = 5,
                            CategoryId = 1,
                            Description = "Premium vibe with padel + wellness concept — very modern place.",
                            ImageUrl = "/images/activities/padel/ClubHouse.jpg",
                            Location = "Dora",
                            Name = "Club House",
                            Price = 0m
                        },
                        new
                        {
                            Id = 38,
                            ActivityTypeId = 5,
                            CategoryId = 1,
                            Description = "Nice mountain area feel — good if you want to play outside Beirut.",
                            ImageUrl = "/images/activities/padel/PadelTown.jpg",
                            Location = "Ain Anoub (Mount Lebanon)",
                            Name = "Padel town",
                            Price = 0m
                        },
                        new
                        {
                            Id = 39,
                            ActivityTypeId = 5,
                            CategoryId = 1,
                            Description = " Beautiful seaside setting — very cool summer vibe.",
                            ImageUrl = "/images/activities/padel/padelByTheSea.jpg",
                            Location = "Halat (Jbeil coast)",
                            Name = "Padel by The Sea",
                            Price = 0m
                        },
                        new
                        {
                            Id = 40,
                            ActivityTypeId = 5,
                            CategoryId = 1,
                            Description = "One of the most popular padel spots with modern courts and active community.",
                            ImageUrl = "/images/activities/padel/padelHouse.jpg",
                            Location = "Jisr El Bacha – Metn",
                            Name = "Padel House",
                            Price = 0m
                        },
                        new
                        {
                            Id = 41,
                            ActivityTypeId = 6,
                            CategoryId = 1,
                            Description = "Tennis courts inside the luxury Mövenpick resort, offering a premium sports experience near the sea with professional facilities and a relaxing atmosphere.",
                            ImageUrl = "/images/activities/tennis/Movenpick_tennis.jpg",
                            Location = "Raouché, Beirut",
                            Name = "Mövenpick Tennis Courts",
                            Price = 0m
                        },
                        new
                        {
                            Id = 42,
                            ActivityTypeId = 6,
                            CategoryId = 1,
                            Description = "A well-known sports complex featuring quality tennis courts, often used for training, tournaments, and recreational play in a calm mountain setting.",
                            ImageUrl = "/images/activities/tennis/Mt_tennis.jpg",
                            Location = "Ain Saadeh – Metn",
                            Name = "Mont La Salle (Mt. Tennis)",
                            Price = 0m
                        },
                        new
                        {
                            Id = 43,
                            ActivityTypeId = 6,
                            CategoryId = 1,
                            Description = "Modern outdoor tennis courts designed for both practice and competitive play, offering a sporty atmosphere and coaching possibilities.",
                            ImageUrl = "/images/activities/tennis/tennisClub.jpg",
                            Location = "Mount Lebanon",
                            Name = "Tennis Club Lebanon (Private Tennis Club)",
                            Price = 0m
                        },
                        new
                        {
                            Id = 44,
                            ActivityTypeId = 4,
                            CategoryId = 1,
                            Description = "The largest football stadium in Lebanon, hosting major national matches, tournaments, and international events.",
                            ImageUrl = "/images/activities/football/camilleChamoun-stad.jpg",
                            Location = "Beirut",
                            Name = "Camille Chamoun Sports City Stadium",
                            Price = 0m
                        },
                        new
                        {
                            Id = 45,
                            ActivityTypeId = 4,
                            CategoryId = 1,
                            Description = "A major football stadium in northern Lebanon used for league matches and local sports events.",
                            ImageUrl = "/images/activities/football/triploiStadium.jpg",
                            Location = "Tripoli, North Lebanon",
                            Name = "Tripoli Municipal Stadium",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("SmartItineraryRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BudgetPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Travelers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SmartItineraryRequest");
                });

            modelBuilder.Entity("SupportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SupportRequests");
                });

            modelBuilder.Entity("Traveler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Travelers");
                });

            modelBuilder.Entity("TripPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItineraryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TripPlans");
                });

            modelBuilder.Entity("UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JourneyEntry", b =>
                {
                    b.HasOne("Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.HasOne("Senior2.Api.Models.ActivityType", "ActivityType")
                        .WithMany("Places")
                        .HasForeignKey("ActivityTypeId");

                    b.HasOne("Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TripPlan", b =>
                {
                    b.HasOne("Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserPreference", b =>
                {
                    b.HasOne("Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("ActivityTypes");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
