// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senior2.Api.Data;

#nullable disable

namespace Senior2.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220201701_RestoreSeedData")]
    partial class RestoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/categories/activities.jpg",
                            Name = "Activities",
                            Slug = "activities"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/categories/guesthouses.jpg",
                            Name = "Guesthouses",
                            Slug = "guesthouses"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/categories/hotels.jpg",
                            Name = "Hotels",
                            Slug = "hotels"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/categories/restaurants.jpg",
                            Name = "Restaurants",
                            Slug = "restaurants"
                        });
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ActivityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/hiking/chouwen_hike.jpg",
                            Name = "Hiking",
                            Slug = ""
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/swimming/swimming.jpg",
                            Name = "Swimming",
                            Slug = ""
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageUrl = "/images/activities/skiing/skiing.jpg",
                            Name = "Skiing",
                            Slug = ""
                        });
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Traditional Lebanese mountain guesthouse with scenic views.",
                            ImageUrl = "/images/guesthouses/beit-trad/beitTrad_livingRoom.jpg",
                            Location = "Broummana, Lebanon",
                            Name = "Beit Trad Guesthouse",
                            Price = 80m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Charming stay surrounded by nature.",
                            ImageUrl = "/images/guesthouses/charme guesthouse/charme_overview.jpg",
                            Location = "Cedars of God, Lebanon",
                            Name = "Charme Guesthouse",
                            Price = 95m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "A charming guesthouse in the ancient coastal city of Byblos.",
                            ImageUrl = "/images/guesthouses/Beit Faris.jpg",
                            Location = "Byblos, Lebanon",
                            Name = "Beit Faris",
                            Price = 95m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Luxury 5-star hotel overlooking the Mediterranean Sea.",
                            ImageUrl = "/images/hotels/phoenicia.jpg",
                            Location = "Beirut, Lebanon",
                            Name = "Phoenicia Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Modern 5-star city hotel with luxury rooms.",
                            ImageUrl = "/images/hotels/radisson.jpg",
                            Location = "Verdun, Beirut",
                            Name = "Radisson Blu Hotel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Authentic Lebanese fine dining experience.",
                            ImageUrl = "/images/restaurants/emsherif.jpg",
                            Location = "Downtown Beirut, Lebanon",
                            Name = "Em Sherif Restaurant",
                            Price = 50m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Modern Lebanese restaurant with upscale ambiance.",
                            ImageUrl = "/images/restaurants/Bebabel.jpg",
                            Location = "Downtown Beirut, Lebanon",
                            Name = "Bebabel",
                            Price = 50m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Upscale seafood dining experience.",
                            ImageUrl = "/images/restaurants/Babel.jpg",
                            Location = "Dbayeh, Lebanon",
                            Name = "Babel Bay",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Senior2.Api.Models.Place", b =>
                {
                    b.HasOne("Senior2.Api.Models.ActivityType", "ActivityType")
                        .WithMany("Places")
                        .HasForeignKey("ActivityTypeId");

                    b.HasOne("Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("ActivityTypes");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("Senior2.Api.Models.ActivityType", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
