import { useEffect, useState } from "react";
import api from "../services/api";
import "../styles/AdminTrips.css";

export default function AdminTrips() {

  const [trips, setTrips] = useState([]);
  const [search, setSearch] = useState("");
  const [selectedTrip, setSelectedTrip] = useState(null);

  useEffect(() => {

    const fetchTrips = async () => {

      try {

        const res = await api.get("/SmartItinerary");

        setTrips(res.data || []);

      } catch (error) {

        console.error("Error loading trips:", error);

      }

    };

    fetchTrips();

  }, []);

  const filteredTrips = trips.filter((trip) =>
    trip.tripType?.toLowerCase().includes(search.toLowerCase())
  );
const deleteTrip = async (id) => {

  const confirmDelete = window.confirm(
    "Are you sure you want to delete this trip?"
  );

  if (!confirmDelete) return;

  try {

    await api.delete(`/SmartItinerary/${id}`);

    // remove trip from UI
    setTrips(trips.filter((t) => t.id !== id));

  } catch (error) {

    console.error("Error deleting trip:", error);

  }

};
  return (
    <div className="admin-trips">

      <h1>User Trips Management</h1>

      <p className="subtitle">
        View and manage all trips generated by users.
      </p>

      <div className="trip-controls">

        <input
          placeholder="Search trips..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />

      </div>

      <div className="table-wrapper">

        <table className="trip-table">

          <thead>

            <tr>

              <th>ID</th>
              <th>Trip Type</th>
              <th>Created By</th>
              <th>Dates</th>
              <th>Budget / Day</th>
              <th>Status</th>
              <th>Actions</th>

            </tr>

          </thead>

          <tbody>

            {filteredTrips.map((trip) => (

              <tr key={trip.id}>

                <td>#{trip.id}</td>

                <td className="trip-name">
                  {trip.tripType}
                </td>

                <td className="created-by">
                  👤 {trip.userName || `User ${trip.userId}`}
                </td>

                <td>
                  {new Date(trip.startDate).toLocaleDateString()} →
                  {new Date(trip.endDate).toLocaleDateString()}
                </td>

                <td>${trip.budgetPerDay}</td>

                <td>
                <span className={`status-badge ${trip.status?.toLowerCase()}`}>
  {trip.status}
</span>
                </td>

                <td className="actions">

                  <button
                    className="view"
                    onClick={() => setSelectedTrip(trip)}
                  >
                    View
                  </button>

                 <button
  className="delete"
  onClick={() => deleteTrip(trip.id)}
>
  Delete
</button>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>


      {/* MODAL */}

      {selectedTrip && (

        <div
          className="modal-overlay"
          onClick={() => setSelectedTrip(null)}
        >

          <div
            className="modal"
            onClick={(e) => e.stopPropagation()}
          >

            <div className="modal-header">

              <h2>{selectedTrip.tripType} Trip</h2>

              <button
                className="close-btn"
                onClick={() => setSelectedTrip(null)}
              >
                Close
              </button>

            </div>

            <div className="modal-grid">

              <div>
                <span>User</span>
                <p>{selectedTrip.userName || `User ${selectedTrip.userId}`}</p>
              </div>

              <div>
                <span>Travelers</span>
                <p>{selectedTrip.travelers}</p>
              </div>

              <div>
                <span>Dates</span>
                <p>
                  {new Date(selectedTrip.startDate).toLocaleDateString()}
                  {" → "}
                  {new Date(selectedTrip.endDate).toLocaleDateString()}
                </p>
              </div>

              <div>
                <span>Budget</span>
                <p>${selectedTrip.budgetPerDay} / day</p>
              </div>

              <div>
                <span>Transport</span>
                <p>{selectedTrip.transport}</p>
              </div>

              <div>
                <span>Created</span>
                <p>
                  {new Date(selectedTrip.createdAt).toLocaleDateString()}
                </p>
              </div>

            </div>

            <div className="activities-section">

              <h3>Activities</h3>

              <div className="activities">

                {(JSON.parse(selectedTrip.activitiesJson || "[]")).map((a,i)=>(
                  <span key={i}>{a}</span>
                ))}

              </div>

            </div>

          </div>

        </div>

      )}

    </div>
  );
}